# print("Hello World")
# print("Hello Again")
# print("I like typing this.")
# print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("Another line to the list.")
print("This sentence is false.")
print("All sentences, including this one, are false.")